### ISSUE TITLE
About activation layer and inference:

### ISSUE THREAD

**Issue by chuong98** [zeiss-microscopy/BSConv#4]
Hello, thanks for releasing the code. I have a couple of questions:
+ I want to confirm about the BSConv-S. In my understand, the module has:
   `bsconvS =[ (Conv1x1 +BN) -->(Conv1x1+BN)-->(dw-Conv3x3)]`
   and the BN and ReLu are only applied after bsconvS. **There is no Activation in the middle of BSConv-S.**
   Is this also hold for the _BS Residual-Inverted Bottleneck_ of Mobile-V2? So that, the transformed block only has 1 activation only at the end. (while original one has 2 ReLU). Specifically:
Inverted-Residual Block:
`x--> [conv1x1-BN-Act --> conv3x3-BN-Act --> conv1x1-BN] + x `
while BS-Inverted Bottleneck:
`x--> [conv1x1-BN  --> conv1x1-BN--> conv3x3-BN-Act] + x `

+ If there is no ReLu in middle of BSCon-S, then during inference,  can we merge the first 2 Conv1x1 into a single conv1x1 (which reduce to BSConv-U), to save computation.
+ Did you compare inference speed between BSConv-S and regular Conv.

Thank you.

**Comment by zeiss-mamthor** [comment]
Hi,
* It is correct that there is no activation after both 1x1 convolution layers. This applies to our modules as well as for almost all replacements (e.g., ResNets, WRNs, VGGs, etc.). For our MobileNet experiments, however, we retain the original structure of the inverted residual bottleneck as it was extensively analyzed in the MobileNet paper that such an arrangement of (i) placing residuals in the bottleneck path and (ii) using an intermediate activation for the distributing 1x1 conv is beneficial. But there is no activation in the bottleneck, which would affect the subspace transformation.
* When merging both 1x1 conv layers for inference, you will have the same output as for BSConvS, but at the FLOP count of BSConvU. This is because you actually reverse the matrix factorization of Eqn. 8 in the paper.
* We noticed speed-ups, but we did not perform a quantitative evaluation. Also note that it is heavily influenced by the actual implementation and used hardware, as it all depends on the support of an optimized implementation for depthwise convolutions.
